#!/usr/bin/env python3
"""Generate OpenAPI JSON schemas for all FastAPI services.

Usage:
    python scripts/generate_openapi.py

Each service's schema is written to openapi/{service-name}.json.
Schemas are generated by importing each FastAPI app directly (no running server needed).
The script uses each service's Poetry virtualenv via `poetry run`.

In a pre-commit hook, modified schema files are automatically staged so they
are included in the current commit.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
OPENAPI_DIR = REPO_ROOT / "openapi"

SERVICES = [
    ("backend/auth-service", "auth-service.json"),
    ("backend/task-service", "task-service.json"),
    ("backend/analytics-service", "analytics-service.json"),
]

# Minimal env vars to satisfy pydantic-settings validation at import time.
# These are not used at runtime — openapi() never connects to the database.
DUMMY_ENV = {
    "DATABASE_URL": "postgresql+asyncpg://dummy:dummy@localhost/dummy",
    "REDIS_URL": "redis://localhost:6379",
    "AUTH_SERVICE_URL": "http://localhost:8000",
    "JWT_PRIVATE_KEY_PATH": "/dev/null",
    "JWT_PUBLIC_KEY_PATH": "/dev/null",
}

# Inline Python fragment run inside each service's venv.
# Imports the FastAPI app, calls .openapi(), and prints JSON to stdout.
_INLINE = "import json,sys; from app.main import app; json.dump(app.openapi(), sys.stdout, indent=2, ensure_ascii=False)"


def generate(service_dir: Path, output_file: Path) -> None:
    env = {**os.environ, **DUMMY_ENV}
    result = subprocess.run(
        ["poetry", "run", "python", "-c", _INLINE],
        cwd=service_dir,
        capture_output=True,
        text=True,
        env=env,
    )
    if result.returncode != 0:
        print(f"\n[ERROR] {service_dir.name}", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    OPENAPI_DIR.mkdir(exist_ok=True)
    output_file.write_text(result.stdout + "\n")
    print(f"  ✓  {output_file.name}")


def main() -> None:
    print("Generating OpenAPI schemas…")
    for service_name, output_name in SERVICES:
        service_dir = REPO_ROOT / service_name
        output_file = OPENAPI_DIR / output_name
        generate(service_dir, output_file)

    # Stage updated schemas so they are included in the current commit.
    subprocess.run(["git", "add", str(OPENAPI_DIR)], cwd=REPO_ROOT, check=True)
    print("Done — openapi/ staged.")


if __name__ == "__main__":
    main()
